[package]
name = "dof-calc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
termion = "4.0.5"
textwrap = "0.16.2"
toml = "0.8.23"
